theme: jekyll-theme-minimal
title: CIT 281 - Project 2
description: Gained experience using git via your CLI and Visual Studio Code (VSCode) Source Control, gained experience writing and executing non-web server Node.js JavaScript code, practiced refactoring JavaScript code.
